baseURL = "mistermboy.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Pablo Menéndez"
theme = "KeepIt"
publishDir = "docs"


paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"



[params]
    since = 2019
    author = "Pablo Menéndez"           # Author's name
    subtitle = "Software Engineer Undergraduate"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other


    avatar = "/images/avatar.png" #comment it to use gravatar

[params.social]
    GitHub = "mistermboy"
    Linkedin = "pablo-menéndez-suárez-106262a7"
    Twitter = "Mistermboy97"
    Email   = "pmenendz@gmail.com"
   

[params.share]
Twitter = true
Linkedin = true

